name: Playwright Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  sanity:
    name: Run Sanity Tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.0-jammy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Sanity tests
        run: npx playwright test --grep @sanity --reporter=json > sanity-results.json

      - name: Parse results
        id: results
        run: |
          PASSED=$(jq '.suites[].specs[].tests[] | select(.status=="passed") | .status' sanity-results.json | wc -l)
          FAILED=$(jq '.suites[].specs[].tests[] | select(.status=="failed") | .status' sanity-results.json | wc -l)
          echo "passed=$PASSED" >> $GITHUB_OUTPUT
          echo "failed=$FAILED" >> $GITHUB_OUTPUT

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sanity-report
          path: playwright-report

      - name: Notify Microsoft Teams
        if: always()
        run: |
          STATUS="✅ Passed"
          if [ "${{ steps.results.outputs.failed }}" != "0" ]; then STATUS="❌ Failed"; fi
          curl -H 'Content-Type: application/json' \
            -d "{
                  \"text\": \"Sanity Tests: $STATUS\n✅ Passed: ${{ steps.results.outputs.passed }}\n❌ Failed: ${{ steps.results.outputs.failed }}\nWorkflow: $GITHUB_WORKFLOW\nRun: $GITHUB_RUN_URL\"
                }" \
            ${{ secrets.MS_TEAMS_WEBHOOK }}

  regression:
    name: Run Regression Tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.0-jammy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Regression tests
        run: npx playwright test --grep @regression --reporter=json > regression-results.json

      - name: Parse results
        id: results
        run: |
          PASSED=$(jq '.suites[].specs[].tests[] | select(.status=="passed") | .status' regression-results.json | wc -l)
          FAILED=$(jq '.suites[].specs[].tests[] | select(.status=="failed") | .status' regression-results.json | wc -l)
          echo "passed=$PASSED" >> $GITHUB_OUTPUT
          echo "failed=$FAILED" >> $GITHUB_OUTPUT

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: regression-report
          path: playwright-report

      - name: Notify Microsoft Teams
        if: always()
        run: |
          STATUS="✅ Passed"
          if [ "${{ steps.results.outputs.failed }}" != "0" ]; then STATUS="❌ Failed"; fi
          curl -H 'Content-Type: application/json' \
            -d "{
                  \"text\": \"Regression Tests: $STATUS\n✅ Passed: ${{ steps.results.outputs.passed }}\n❌ Failed: ${{ steps.results.outputs.failed }}\nWorkflow: $GITHUB_WORKFLOW\nRun: $GITHUB_RUN_URL\"
                }" \
            ${{ secrets.MS_TEAMS_WEBHOOK }}
