name: Playwright Tests

on:
  workflow_dispatch:   # manual trigger
  schedule:            # scheduled trigger (UTC time)
    - cron: "0 6 * * *"   # runs every day at 06:00 UTC

jobs:
  sanity:
    name: Run Sanity Tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.0-jammy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run Sanity tests
        run: npx playwright test --grep @sanity --reporter=json > sanity-results.json || true

      - name: Parse results
        id: results
        run: |
          PASSED=$(jq '[.. | objects | select(has("status")) | .status] | map(select(.=="passed")) | length' sanity-results.json)
          FAILED=$(jq '[.. | objects | select(has("status")) | .status] | map(select(.=="failed")) | length' sanity-results.json)
          echo "passed=$PASSED" >> $GITHUB_OUTPUT
          echo "failed=$FAILED" >> $GITHUB_OUTPUT

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sanity-report
          path: playwright-report

      - name: Notify Microsoft Teams
        if: always()
        run: |
          STATUS="✅ Passed"
          if [ "${{ steps.results.outputs.failed }}" != "0" ]; then STATUS="❌ Failed"; fi
          curl -H 'Content-Type: application/json' \
            -d "{
                  \"text\": \"Sanity Tests: $STATUS\n✅ Passed: ${{ steps.results.outputs.passed }}\n❌ Failed: ${{ steps.results.outputs.failed }}\nWorkflow: $GITHUB_WORKFLOW\nRun: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"
                }" \
            ${{ secrets.MS_TEAMS_WEBHOOK }}

  regression:
    name: Run Regression Tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.0-jammy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run Regression tests
        run: npx playwright test --grep @regression --reporter=json > regression-results.json || true

      - name: Parse results
        id: results
        run: |
          PASSED=$(jq '[.. | objects | select(has("status")) | .status] | map(select(.=="passed")) | length' regression-results.json)
          FAILED=$(jq '[.. | objects | select(has("status")) | .status] | map(select(.=="failed")) | length' regression-results.json)
          echo "passed=$PASSED" >> $GITHUB_OUTPUT
          echo "failed=$FAILED" >> $GITHUB_OUTPUT

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: regression-report
          path: playwright-report

      - name: Notify Microsoft Teams
        if: always()
        run: |
          STATUS="✅ Passed"
          if [ "${{ steps.results.outputs.failed }}" != "0" ]; then STATUS="❌ Failed"; fi
          curl -H 'Content-Type: application/json' \
            -d "{
                  \"text\": \"Regression Tests: $STATUS\n✅ Passed: ${{ steps.results.outputs.passed }}\n❌ Failed: ${{ steps.results.outputs.failed }}\nWorkflow: $GITHUB_WORKFLOW\nRun: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"
                }" \
            ${{ secrets.MS_TEAMS_WEBHOOK }}
