name: Playwright Tests

on:
  workflow_dispatch:   # manual trigger
  schedule:            # scheduled trigger (UTC time)
    - cron: "0 6 * * *"   # runs every day at 06:00 UTC

jobs:
  sanity:
    name: Run Sanity Tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.0-jammy # official playwright docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Sanity tests
        run: npx playwright test --grep @sanity --reporter=list,json

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sanity-report
          path: playwright-report

      - name: Notify Microsoft Teams
        if: always()
        run: |
          STATUS="✅ Passed"
          if [ "${{ job.status }}" != "success" ]; then STATUS="❌ Failed"; fi
          curl -H 'Content-Type: application/json' \
            -d "{\"text\":\"Sanity Tests: $STATUS\nWorkflow: $GITHUB_WORKFLOW\nRun: $GITHUB_RUN_URL\"}" \
            ${{ secrets.MS_TEAMS_WEBHOOK }}

  regression:
    name: Run Regression Tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.0-jammy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Regression tests
        run: npx playwright test --grep @regression --reporter=list,json

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: regression-report
          path: playwright-report

      - name: Notify Microsoft Teams
        if: always()
        run: |
          STATUS="✅ Passed"
          if [ "${{ job.status }}" != "success" ]; then STATUS="❌ Failed"; fi
          curl -H 'Content-Type: application/json' \
            -d "{\"text\":\"Regression Tests: $STATUS\nWorkflow: $GITHUB_WORKFLOW\nRun: $GITHUB_RUN_URL\"}" \
            ${{ secrets.MS_TEAMS_WEBHOOK }}
